Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -186,10 +186,17 @@ jobs:
       id: organize
       if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
       run: |
-        cd openwrt/bin/targets/*/*
-        rm -rf packages
-        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
-        echo "status=success" >> $GITHUB_OUTPUT
+        set -e  # 确保脚本遇到错误时立即退出
+        if [ -d openwrt/bin/targets ]; then
+          cd openwrt/bin/targets/*/* || exit 1
+          rm -rf packages || exit 1
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV || exit 1
+          echo "status=success" >> $GITHUB_OUTPUT || exit 1
+        else
+          echo "Error: Directory 'openwrt/bin/targets' not found!" >&2
+          exit 1
+        fi
+
 	
     - name: Upload firmware directory
       uses: actions/upload-artifact@main
